version: "3.7"

services:
    mariadb:
        build:
            context: ./requirements/mariadb/.
            args:
                - MYSQL_PASSWORD
                - MYSQL_ROOT_PASSWORD
                - WP_DB_USER
                - WP_PASSWORD
                - WP_DB_NAME
                 
        image: mariadb
        container_name: mariadb
        volumes:
            - database:/var/lib/mysql
        networks:
            my_network:
                aliases:
                    - $MARIADB_NET

    wordpress:
        environment:
            - WP_DB_USER
            - WP_PASSWORD
            - WP_DB_NAME
            - WP_ADMIN_USER
            - WP_ADMIN_PWD
            - MARIADB_NET
        build: ./requirements/wordpress/.
        image: wordpress
        container_name: wordpress
        ports:
            - "9000:9000"
        depends_on:
            - "mariadb"
        volumes:
            - wp-files:/wordpress
        networks:
            my_network:
                aliases:
                    - $WORDPRESS_NET

    nginx:
        build:
            context: ./requirements/nginx/.
            args:
                - WORDPRESS_NET
        image: nginx
        container_name: nginx
        ports:
            - "443:443"
        depends_on:
            - "wordpress"
        volumes:
            - wp-files:/wordpress
        networks:
            my_network:
                aliases:
                    - $NGINX_NET

volumes:
    wp-files:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $WP_FILES
    database:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $DB_FILES

networks:
    my_network:
        name: my_network

