version: "3.7"

services:
    mariadb:
        build: ./requirements/mariadb/.
        image: mariadb
        container_name: mariadb
        networks:
            my_network:
                aliases:
                    - mariadb_net 

    wordpress:
        build: ./requirements/wordpress/.
        image: wordpress
        container_name: wordpress
        ports:
            - "9000:9000"
        depends_on:
            - "mariadb"
        volumes:
            - ./tmp_files:/var/www/html/wordpress
        networks:
            my_network:
                aliases:
                    - wordpress_net

    nginx:
        build: ./requirements/nginx/.
        image: nginx
        container_name: nginx
        ports:
            - "443:443"
        depends_on:
            - "wordpress"
        volumes:
            - ./tmp_files:/var/www/html/wordpress
        networks:
            my_network:
                aliases:
                    - nginx_net 

networks:
    my_network:
        name: my_network

