FROM alpine:3.15

#WORKDIR /

# installing nginx:
RUN apk add openssl curl ca-certificates
RUN printf "%s%s%s\n" "http://nginx.org/packages/alpine/v" \
`egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release` "/main" \
| tee -a /etc/apk/repositories
RUN curl -o /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub
RUN mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/
RUN apk add nginx

COPY ./data /data
COPY ./ajuncosa.42.fr.conf /etc/nginx/conf.d/ 

#CMD ["nginx"]

ENTRYPOINT nginx && sh 

# EXPOSE
